orbs:
  my-orb:
    commands:
      checkout:
        parameters:
          checkout_merge:
            default: false
            type: boolean
        steps:
          - run:
              name: Download Github Zip
              command: |
                REF="$CIRCLE_SHA1"
                OUTPUT_DIRECTORY="$CIRCLE_PROJECT_REPONAME-$REF"
                <<# checkout_merge >>
                if [ -n "$CIRCLE_PULL_REQUEST" ] && [ "$CIRCLE_BRANCH" != "develop" ]; then
                  # Checkout merge if this is a PR
                  PR_NUMBER=$(basename $CIRCLE_PULL_REQUEST)
                  REF="pull/$PR_NUMBER/head"
                  OUTPUT_DIRECTORY="$CIRCLE_PROJECT_REPONAME-pull-$PR_NUMBER-head"
                fi
                <</ checkout_merge >>
                cd ~
                # Expand ~ in working directory path path
                WD="${CIRCLE_WORKING_DIRECTORY/#\~/$HOME}"
                rm -rf "$WD"
                curl -s#L "https://github.com/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/archive/$REF.zip" | bsdtar -xvf-
                mv "$OUTPUT_DIRECTORY" "$WD"

version: 2.1
jobs:
  build_and_test:
    macos:
      xcode: "10.1.0"
    steps:
      - my-orb/checkout
      - restore_cache:
          keys:
            - wordpress-ios-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Podfile.lock" }}
            - wordpress-ios-dependencies-{{ checksum "Gemfile.lock" }}
            - wordpress-ios-dependencies-
      - run:
          name: Bundle install
          command: bundle install --path=vendor/bundle
      - run:
          name: CocoaPods Check
          command: (bundle exec pod check && touch .skip_pod_install) || echo "Pods will be updated"
      - run:
          name: Fetch CocoaPods Specs (if needed)
          command: test -e .skip_pod_install || curl https://cocoapods-specs.circleci.com/fetch-cocoapods-repo-from-s3.sh | bash -s cf
      - run:
          name: Pod Install (if needed)
          command: test -e .skip_pod_install || bundle exec pod install
          environment:
            COCOAPODS_DISABLE_STATS: true
      - save_cache:
          key: wordpress-ios-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "Podfile.lock" }}
          paths:
            - Pods/
            - vendor/bundle
      - run:
          name: Build
          command: xcodebuild -scheme "WordPress" -configuration "Debug" -workspace "WordPress.xcworkspace" -sdk iphonesimulator build-for-testing | bundle exec xcpretty
      - run:
          name: Test
          command: xcodebuild -scheme "WordPress" -configuration "Debug" -workspace "WordPress.xcworkspace" -destination 'platform=iOS Simulator,name=iPhone XS,OS=latest' test-without-building | bundle exec xcpretty -r junit
      - store_test_results:
          path: build/reports

  danger:
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - wordpress-ios-danger-gems-v2-{{ checksum "Rakefile" }}-{{ checksum "Gemfile.lock" }}
            - wordpress-ios-danger-gems-v2-{{ checksum "Rakefile" }}
            - wordpress-ios-danger-gems-v2-
      - run:
          name: Bundle install
          command: bundle install --path=vendor/bundle
      - save_cache:
          key: wordpress-ios-danger-gems-v2-{{ checksum "Rakefile" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/
      - run:
          name: Danger
          command: |
            if [ -n "$DANGER_GITHUB_API_TOKEN" ]; then
              bundle exec danger --fail-on-errors=true
            else
              echo "Not running danger because $DANGER_GITHUB_API_TOKEN is not found"
            fi

workflows:
  version: 2
  wordpress_ios:
    jobs:
      - danger:
          filters:
            branches:
              # Disable Danger on develop
              ignore: develop
      - build_and_test
